name: Test partial eval

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ocaml/opam:ubuntu-ocaml-4.09
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Do the test!
        run: |
          sudo apt-get install gmp mpir
          opam install menhir ocamlfind ott linenoise pprint z3.4.7.1
          eval `opam config env`
          export LD_LIBRARY_PATH=`opam config var z3:lib`
          dune test