name: Test partial eval

on:
  push:
    branches:
      - partial_eval 
  pull_request:
    types: []
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/uq-pac/asli-base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Extract encodings
        run: tar xzf encodings.tar.gz 
      
      - name: opam install
        run: |
          eval `opam env`
          opam install . --deps-only --with-test

      - name: Build
        run: |
          eval `opam env`
          dune build

      - name: Test
        id: test
        run: |
          eval `opam env`
          export LD_LIBRARY_PATH=`opam config var z3:lib`
          scripts/coverage.sh test

      - name: Upload new coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-output-${{ github.run_id }}
          path: ${{ steps.test.outputs.OUTPUT }}
