name: Test partial eval

on:
  push:
    branches:
      - partial_eval
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.09.0
          dune-cache: true

      - name: Opam install
        run: |
          opam switch create new 4.09.0
          wget https://github.com/katrinafyi/pac-environment/releases/download/opam/new.tar.gz
          tar xzf new.tar.gz
          mv new ~/.opam

      - name: Extract encodings
        run: tar xzf encodings.tar.gz

      - name: Build and test
        id: test
        run: |
          opam switch new
          eval `opam config env`
          export LD_LIBRARY_PATH=`opam config var z3:lib`
          dune build
          ./coverage.sh test

      - name: Upload new coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-output-${{ github.run_id }}
          path: ${{ steps.test.outputs.OUTPUT }}
