name: Test partial eval

on:
  push:
    branches:
      - partial_eval 
  pull_request:
    types: []
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
        # XXX using multi-line string will fail since \n is stuck to the end of the argument.
        shell: "nix develop github:katrinafyi/pac-nix#ocamlPackages_pac.asli --impure --accept-flake-config --command bash --noprofile --norc -eo pipefail {0}"

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v25
    - run: echo 'preparing nix shell environment'

    - run: dune build --profile release
    - run: dune runtest -j4
    - run: dune build '@coverage' -j4
    - run: |
        echo "OUTPUT=$(pwd)/_build/default/tests/coverage" >> $GITHUB_OUTPUT
        rm -rf _build/default/tests/coverage/encodings
      id: coverage
    - run: sudo apt-get update && sudo apt-get install clang-15 lld-15 meson ninja-build
    - run: offlineASL-cpp/build.sh
      env:
        CXX: "/usr/bin/clang++-15"
        CXX_LD: "/usr/bin/ld.lld-15"

    - name: Upload new coverage results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-output-${{ github.run_id }}
        path: ${{ steps.coverage.outputs.OUTPUT }}
