name: Test partial eval

on:
  push:
    branches:
      - partial_eval 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.09.0

      - name: Opam install
        run: opam install . --deps-only --with-test

      - name: Environment setup
        run: |
          eval `opam config env`
          export LD_LIBRARY_PATH=`opam config var z3:lib`

      - name: Build
        run: dune build

      - name: Test
        run: dune runtest