name: Test partial eval

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.09.0

      - name: Do the test!
        run: |
          opam install . --deps-only --with-test
          eval `opam config env`
          export LD_LIBRARY_PATH=`opam config var z3:lib`
          dune build
          dune runtest