name: Test partial eval

on:
  push:
    branches:
      - partial_eval 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.09.0
          dune-cache: true

      - name: Opam install
        run: opam install . --deps-only --with-test

      - name: Build and test
        id: test
        run: |
          eval `opam config env`
          export LD_LIBRARY_PATH=`opam config var z3:lib`
          dune build
          ./coverage.sh test

      - name: Upload new coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-output
          path: ${{ steps.test.outputs.OUTPUT }}
